apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    app: guestbook-ui
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      serviceAccountName: team-riker
      containers:
      - image: 111442077524.dkr.ecr.us-west-2.amazonaws.com/group3-api:v5
        name: guestbook-ui
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: '400Mi'
            cpu: '100m'
          limits:
            memory: '600Mi'
            cpu: '200m'
        securityContext:
          privileged: false
          #readOnlyRootFilesystem: false # guestbook neet to write to /var/run/apache2/apache2.pid
          allowPrivilegeEscalation: false
